### ISSUE TITLE
Avoir les numéros de coop dans les exports CSV depuis le logiciel des membres

### ISSUE THREAD

**Issue by Vallllll** [Les400Coop/gestion-compte#7]
Lorsqu'on exporte les mails on a les champs nom, prénom, mail, si on pouvait avoir le numéro en + ce serait top !

**Comment by SebFalque** [comment]
La premiere colonne de l'export des adherent est bien le numéro d'adhérent officiel

**Comment by Vallllll** [comment]
en fait c'était aussi le sujet évoqué par FredA sur le n° à 8 chiffres
